setup:
  runner: train_dpdm_base
  n_gpus_per_node: 4
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6021
  omp_n_threads: 64
data:
  path: data/raw/dead_leaves-0-1_bw
  imagepath: data/raw/dead_leaves-0-1_bw
  name: dead_leaves_bw-0-1_28
  num_channels: 1
  resolution: 28
  n_classes: 10
  fid_stats: 
  - assets/stats/mnist_train.npz
  one_hot: False
  dataloader_params:
    num_workers: 1
    pin_memory: True
model:
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  network:
    image_size: 28
    attn_resolutions:
    - 7
optim:
  optimizer: Adam
  params:
    lr: 4e-4
    weight_decay: 0.
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  snapshot_batch_size: 64
  fid_batch_size: 64
train:
  seed: 0
  batch_size: 128
  n_epochs: 300
  log_freq: 100
  snapshot_freq: 1000
  snapshot_threshold: 1
  save_freq: 100000
  save_threshold: 1
  fid_freq: 10000
  fid_samples: 5000
  fid_threshold: 1
loss: 
  version: edm
  p_mean: -1.2
  p_std: 1.2
  n_noise_samples: 4
  n_classes: 10
  log_tau: 2
  cleaning: False
  coarse: True
dp:
  max_grad_norm: None
  delta: None
  epsilon: None
  max_physical_batch_size: None
  n_splits: None